//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiInteligente2022.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiInteligente2022.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        internal static string AboutAppVersion {
            get {
                return ResourceManager.GetString("AboutAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string AboutDeviceModel {
            get {
                return ResourceManager.GetString("AboutDeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string AboutDeviceName {
            get {
                return ResourceManager.GetString("AboutDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevicePlatform.
        /// </summary>
        internal static string AboutDevicePlatform {
            get {
                return ResourceManager.GetString("AboutDevicePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Version.
        /// </summary>
        internal static string AboutDeviceSystemVersion {
            get {
                return ResourceManager.GetString("AboutDeviceSystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string AboutManufacturer {
            get {
                return ResourceManager.GetString("AboutManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string BranchDetailTitle {
            get {
                return ResourceManager.GetString("BranchDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        internal static string CurrentLocationLabel {
            get {
                return ResourceManager.GetString("CurrentLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishButton {
            get {
                return ResourceManager.GetString("FinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting location.
        /// </summary>
        internal static string GetLocationErrorTitle {
            get {
                return ResourceManager.GetString("GetLocationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device has no geolocation enable.
        /// </summary>
        internal static string GetLocationNotEnabledError {
            get {
                return ResourceManager.GetString("GetLocationNotEnabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not support location is required.
        /// </summary>
        internal static string GetLocationNotSupportedError {
            get {
                return ResourceManager.GetString("GetLocationNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission for geolocation.
        /// </summary>
        internal static string GetLocationPermissionError {
            get {
                return ResourceManager.GetString("GetLocationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguagePageSubtitle {
            get {
                return ResourceManager.GetString("LanguagePageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Language.
        /// </summary>
        internal static string LanguagePageTitle {
            get {
                return ResourceManager.GetString("LanguagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Route.
        /// </summary>
        internal static string LocationShowRoute {
            get {
                return ResourceManager.GetString("LocationShowRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string LocationsTitle {
            get {
                return ResourceManager.GetString("LocationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during login. Please check your credentials.
        /// </summary>
        internal static string LoginAlertError {
            get {
                return ResourceManager.GetString("LoginAlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string LoginPageSignupButton {
            get {
                return ResourceManager.GetString("LoginPageSignupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write a password.
        /// </summary>
        internal static string LoginPasswordError {
            get {
                return ResourceManager.GetString("LoginPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("LoginPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginUserAlertTitle {
            get {
                return ResourceManager.GetString("LoginUserAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write a user name.
        /// </summary>
        internal static string LoginUserError {
            get {
                return ResourceManager.GetString("LoginUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string LoginUserPlaceHolder {
            get {
                return ResourceManager.GetString("LoginUserPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string MainMenuLocations {
            get {
                return ResourceManager.GetString("MainMenuLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MainMenuLogout {
            get {
                return ResourceManager.GetString("MainMenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        internal static string MainMenuNewReport {
            get {
                return ResourceManager.GetString("MainMenuNewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MainMenuReports {
            get {
                return ResourceManager.GetString("MainMenuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        internal static string MainMenuSubtitle {
            get {
                return ResourceManager.GetString("MainMenuSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string MainMenuSync {
            get {
                return ResourceManager.GetString("MainMenuSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string PinLabelDestination {
            get {
                return ResourceManager.GetString("PinLabelDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amout:.
        /// </summary>
        internal static string ReportsAmout {
            get {
                return ResourceManager.GetString("ReportsAmout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        internal static string ReportsClient {
            get {
                return ResourceManager.GetString("ReportsClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string ReportsDate {
            get {
                return ResourceManager.GetString("ReportsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string SignupAddressPlaceholder {
            get {
                return ResourceManager.GetString("SignupAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during user creation.
        /// </summary>
        internal static string SignupAlertErrorUserCreation {
            get {
                return ResourceManager.GetString("SignupAlertErrorUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was created successfully.
        /// </summary>
        internal static string SignupAlertSuccessUserCreation {
            get {
                return ResourceManager.GetString("SignupAlertSuccessUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string SignUpCreateButton {
            get {
                return ResourceManager.GetString("SignUpCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Credentials.
        /// </summary>
        internal static string SignupCredentials {
            get {
                return ResourceManager.GetString("SignupCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string SignupEmailPlaceholder {
            get {
                return ResourceManager.GetString("SignupEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write an address.
        /// </summary>
        internal static string SignupInvalidAddressMessage {
            get {
                return ResourceManager.GetString("SignupInvalidAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write a valid email.
        /// </summary>
        internal static string SignupInvalidEmailMessage {
            get {
                return ResourceManager.GetString("SignupInvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must meet the following requirements:
        ///- At least 1 lowercase
        ///- At least 1 uppercase
        ///- At least 1 number
        ///- At least 1 special character @$!%*?&amp;
        ///- The minimum length is 8 characters.
        /// </summary>
        internal static string SignupInvalidPasswordMessage {
            get {
                return ResourceManager.GetString("SignupInvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number must meet this format +55 12345678.
        /// </summary>
        internal static string SignupInvalidPhoneNumberMessage {
            get {
                return ResourceManager.GetString("SignupInvalidPhoneNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must write an user name.
        /// </summary>
        internal static string SignupInvalidUserNameMessage {
            get {
                return ResourceManager.GetString("SignupInvalidUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignupPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SignupPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Personal Info.
        /// </summary>
        internal static string SignupPersonalData {
            get {
                return ResourceManager.GetString("SignupPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string SignupPhonePlaceholder {
            get {
                return ResourceManager.GetString("SignupPhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string SignupSubtitle {
            get {
                return ResourceManager.GetString("SignupSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string SignupTitle {
            get {
                return ResourceManager.GetString("SignupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SignupUserPlaceholder {
            get {
                return ResourceManager.GetString("SignupUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string SignupUsertAlertTitle {
            get {
                return ResourceManager.GetString("SignupUsertAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string SplashWelcome {
            get {
                return ResourceManager.GetString("SplashWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string SyncTitle {
            get {
                return ResourceManager.GetString("SyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree Terms and Condition.
        /// </summary>
        internal static string TermsAcceptButton {
            get {
                return ResourceManager.GetString("TermsAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLUF.
        /// </summary>
        internal static string TermsPageSubtitle {
            get {
                return ResourceManager.GetString("TermsPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditios.
        /// </summary>
        internal static string TermsPageTitle {
            get {
                return ResourceManager.GetString("TermsPageTitle", resourceCulture);
            }
        }
    }
}
